steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/crack-node-287504/gceme:1", "."]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/crack-node-287504/gceme:1"]
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s.yaml
      - --image=gcr.io/crack-node-287504/gceme:1
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}